//
//  User.swift
//  Challenge
//
//  Created by Kevin on 6/28/18.
//  Copyright © 2018 Kevin. All rights reserved.
//

import Foundation
import FirebaseDatabase


//Create object that contains every aspect of the users
//Has two different constructors: the first one to create a user programatically and manually
// The second one to create  an object using a DataSnapshot generated by FirebaseDatabase
struct User {
    
    let name: String!
    let age: Int!
    let	gender: String!
    let hobbies: String!
    let id: Int!
    let image: String!
    let itemRef:DatabaseReference?
    
    init (name:String, age:Int, gender:String, hobbies: String, id: Int, image: String){
        self.name = name
        self.age = age
        self.gender = gender
        self.hobbies = hobbies
        self.id = id
        self.image = image
        self.itemRef = nil
    }
    
    init (snapshot:DataSnapshot){
        
        itemRef = snapshot.ref
        
        if let snapshot_name = snapshot.childSnapshot(forPath: "Name").value as? String { //try to recieve the value from key: "Name"
            name = snapshot_name //if found then equal it to the name value of the object
        }else {
            name = "Anonymous" // if no name is found
        }
        
        if let snapshot_age = snapshot.childSnapshot(forPath: "Age").value as? Int { //try to recieve the value from key: "Age"
            age = snapshot_age //if found then equal it to the age value of the object
        }else {
            age = 000 // if no age is found
        }
        
        if let snapshot_gender = snapshot.childSnapshot(forPath: "Gender").value as? String {
            gender = snapshot_gender
        }else {
            gender = "Unknown"
        }
        
        if let snapshot_hobbies = snapshot.childSnapshot(forPath: "Hobbies").value as? String {
            hobbies = snapshot_hobbies
        }else {
            hobbies = "Unknown"
        }
        
        if let snapshot_id = snapshot.childSnapshot(forPath: "Id").value as? Int {
            id = snapshot_id
        }else {
            id = 000
        }
        
        if let snapshot_image = snapshot.childSnapshot(forPath: "Image").value as? String {
            image = snapshot_image
        }else {
            image = "Unknown"
        }
    }
 
    
    func toAnyObject() -> AnyObject {// or change to any
        return ["Name":name,"Age":age, "Gender":gender, "Hobbies":hobbies, "Id":id, "Image": image] as NSDictionary
    }
    
}
